#Database
POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: letmein
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5433
POSTGRESQL_DATABASE: postgres

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: thinhle1199@gmail.com
EMAIL_PASSWORD: ThInH1199
VERIFY_EMAIL_HOST: http://localhost:8085